server:
  servlet:
    contextPath: /transfermoney/api
spring:
  datasource:
    url: jdbc:mysql://container_transfermoney_mysql_db:3306/transfermoney_db?useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
stripe:
  api-key: