server:
  servlet:
    contextPath: /transfermoney/api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/database_teste
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
stripe:
  api-key: rk_test_51JAkCFDMphThkf0tLX1SIHQaYFt5ZQjlIDlya42w8nUbrQartGM0NqpJM2dwD9llClf3qgPicmHSAFlJuVzTSY4T00WYMWNk8o